class TimeloopOrchestrator:
    def __init__(self, t_k, t_c, t_out, t_in, r, s):
        """
        Takes the optimized integer tiles from the Mathematical Engine and 
        prepares the 'Virtual Fused Layer' topologies for Timeloop verification.
        """
        self.t_k = t_k
        self.t_c = t_c
        self.t_out = t_out
        self.t_in = t_in
        self.r = r
        self.s = s

    def generate_virtual_layer_prob(self, layer_idx, recalculate_halo=True):
        """
        Dynamically generates the CNN loop bounds for Timeloop to simulate.
        If recalculating the halo, it expands the spatial bounds of Layer 2
        to natively include the redundant computation volume.
        """
        print(f"=== Stage 3: Timeloop Virtual Verification (Layer {layer_idx}) ===")
        
        # Base layer parameters (assuming stride 1)
        prob = {
            "problem": {
                "instance": {
                    "R": self.r,
                    "S": self.s,
                    "C": self.t_c,
                    "K": self.t_k
                }
            }
        }
        
        if layer_idx == 1:
            # Layer 1 produces the intermediate tile (T_in size)
            prob["problem"]["instance"]["P"] = self.t_in
            prob["problem"]["instance"]["Q"] = self.t_in
            print(f"  Layer 1 configured as base producer: {self.t_in}x{self.t_in} spatial output.")
            
        elif layer_idx == 2:
            if recalculate_halo:
                # To trick Timeloop into verifying the recalculation energy, 
                # we set its loop bounds equal to the ENTIRE required input footprint,
                # not just the final output size.
                prob["problem"]["instance"]["P"] = self.t_out + self.r - 1
                prob["problem"]["instance"]["Q"] = self.t_out + self.s - 1
                print(f"  Layer 2 configured as Virtual Fused Layer: {prob['problem']['instance']['P']}x{prob['problem']['instance']['Q']} spatial output.")
                print(f"  -> Timeloop will now physically simulate the {self.t_in**2 - self.t_out**2} redundant MACs implicitly.")
            else:
                # Standard execution (spilled to DRAM)
                prob["problem"]["instance"]["P"] = self.t_out
                prob["problem"]["instance"]["Q"] = self.t_out
                print(f"  Layer 2 configured as standard isolated layer: {self.t_out}x{self.t_out} spatial output.")
                
        return prob

if __name__ == "__main__":
    # Use the tiles generated by Phase 1
    orchestrator = TimeloopOrchestrator(t_k=64, t_c=64, t_out=32, t_in=34, r=3, s=3)
    
    # Generate verification configurations
    l1_prob = orchestrator.generate_virtual_layer_prob(layer_idx=1)
    print()
    l2_prob = orchestrator.generate_virtual_layer_prob(layer_idx=2, recalculate_halo=True)
